//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_pwmsEntities : DbContext
    {
        public db_pwmsEntities()
            : base("name=db_pwmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_addressbook> tb_addressbook { get; set; }
        public virtual DbSet<tb_branch> tb_branch { get; set; }
        public virtual DbSet<tb_business> tb_business { get; set; }
        public virtual DbSet<tb_city> tb_city { get; set; }
        public virtual DbSet<tb_culture> tb_culture { get; set; }
        public virtual DbSet<tb_daywordpad> tb_daywordpad { get; set; }
        public virtual DbSet<tb_duthcall> tb_duthcall { get; set; }
        public virtual DbSet<tb_employee> tb_employee { get; set; }
        public virtual DbSet<tb_employeename> tb_employeename { get; set; }
        public virtual DbSet<tb_family> tb_family { get; set; }
        public virtual DbSet<tb_folk> tb_folk { get; set; }
        public virtual DbSet<tb_individual> tb_individual { get; set; }
        public virtual DbSet<tb_laborage> tb_laborage { get; set; }
        public virtual DbSet<tb_login> tb_login { get; set; }
        public virtual DbSet<tb_popemodel> tb_popemodel { get; set; }
        public virtual DbSet<tb_randp> tb_randp { get; set; }
        public virtual DbSet<tb_rpkind> tb_rpkind { get; set; }
        public virtual DbSet<tb_staffbasic> tb_staffbasic { get; set; }
        public virtual DbSet<tb_trainnote> tb_trainnote { get; set; }
        public virtual DbSet<tb_userpope> tb_userpope { get; set; }
        public virtual DbSet<tb_visage> tb_visage { get; set; }
        public virtual DbSet<tb_wordpad> tb_wordpad { get; set; }
        public virtual DbSet<tb_workresume> tb_workresume { get; set; }
    }
}
