//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_addressbook
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public string QQ { get; set; }
        public string WorkPhone { get; set; }
        public string E_mail { get; set; }
        public string Handset { get; set; }
    }
}
