//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_family
    {
        public string ID { get; set; }
        public string Stu_ID { get; set; }
        public string LeagueName { get; set; }
        public string Nexus { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string WorkUnit { get; set; }
        public string Business { get; set; }
        public string Visage { get; set; }
        public string phone { get; set; }
    }
}
