//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPMS.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_staffbasic
    {
        public string ID { get; set; }
        public string StaffName { get; set; }
        public string Folk { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Age { get; set; }
        public string Culture { get; set; }
        public string Marriage { get; set; }
        public string Sex { get; set; }
        public string Visage { get; set; }
        public string IDCard { get; set; }
        public Nullable<System.DateTime> Workdate { get; set; }
        public Nullable<int> WorkLength { get; set; }
        public string Employee { get; set; }
        public string Business { get; set; }
        public string Laborage { get; set; }
        public string Branch { get; set; }
        public string Duthcall { get; set; }
        public string Phone { get; set; }
        public string Handset { get; set; }
        public string School { get; set; }
        public string Speciality { get; set; }
        public Nullable<System.DateTime> GraduateDate { get; set; }
        public string Address { get; set; }
        public byte[] Photo { get; set; }
        public string BeAware { get; set; }
        public string City { get; set; }
        public Nullable<float> M_Pay { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTime> Pact_B { get; set; }
        public Nullable<System.DateTime> Pact_E { get; set; }
        public Nullable<float> Pact_Y { get; set; }
    }
}
